apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2
        imagePullPolicy: Always
        command: ["redis-server"]
        args: ["/config/redis.conf"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redisdata
        - mountPath: /config
          name: config
      volumes:
        - name: config
          configMap:
            name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redisdata
    spec:
      accessModes: 
      - "ReadWriteOnce"
      storageClassName: "hostpath"
      resources:
        requests:
          storage: 1Gi
