volumes:
  pg-data: ~

services:
  api:
    image: ${IMAGE:-wishlist-api}
    profiles:
      - full
      - cli
    build:
        context: .
        dockerfile: Dockerfile
        target: ${BUILD_TARGET:-runtime}
    env_file:
      - .env
    environment:
      PUBLIC_ADDRESS: ":8080"
      PRIVATE_ADDRESS: ":8081"
    ports:
      - "8080:8080"
      - "8081:8081"
    command: ["system", "core"]
    depends_on:
      - postgres
      - redis
  cli:
    image: ${IMAGE:-wishlist-api}
    profiles:
      - full
      - cli
    build:
        context: .
        dockerfile: Dockerfile
        target: ${BUILD_TARGET:-runtime}
    env_file:
        - .env
    command: ["--help"]
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
    - "8001:5432"
    volumes:
    - "pg-data:/var/lib/postgresql/data/pgdata"
    command: ["postgres", "-c", "log_statement=all"]
  redis:
    image: redis:7
    ports:
    - "8002:6379"
