apiVersion: v1
kind: Secret
metadata:
  name: wishlist-api-secrets
type: Opaque
stringData:
  APP_SECRET: {{ .Values.env.APP_SECRET | quote }}
  POSTGRES_DSN: {{ .Values.env.POSTGRES_DSN | quote }}
  REDIS_DSN: {{ .Values.env.REDIS_DSN | quote }}
---
{{- with .Values.gitlab }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gl-registry-credentials
  annotations:
    helm.sh/resource-policy: keep
stringData:
  .dockerconfigjson: >-
    {
      "auths": {
        "registry.gitlab.com": {
          "auth":"{{ printf "%s:%s" .user .password | b64enc }}"
        }
      }
    }
{{- end }}
